import styles from "./PrivacyPolicy.module.css"

export default function PrivacyPolicy(){
    
    return(
        <section className={styles.cardsMainSection}>
            <section className={styles.cardsSection}>
                <div className={styles.title}>Politika privatnosti</div>
                <div className={styles.desc}>Kompanija HakatonArena, čiji veb sajt ili aplikaciju koristite, poštuje vaše pravo na privatnost kao korisnika naših usluga i zato vas ovom Politikom privatnosti informišemo koje vaše podatke o ličnosti prikupljamo, zašto ih prikupljamo, kako ih koristimo, na koji način ih obrađujemo, kao i koja su vaša prava i na koji način možete da ih ostvarite. Obezbeđujemo da se lični podaci naših Korisnika obrađuju u skladu sa važećim odredbama propisa Republike Srbije kao i u skladu sa važećim odredbama direktive Evropske unije. Politika privatnosti se primenjuje na sve usluge i proizvode čije korišćenje uključuje obradu podataka o ličnosti. Naša Politika privatnosti omogućava Vam da saznate kako obrađujemo lične podatke korisnika naših usluga, kada koristite sajt i/ili aplikaciju, a pre svega: Ko je administrator vaših ličnih podataka, Koje podatke obrađujemo i u koju svrhu, Po kom osnovu obrađujemo podatke, Koliko dugo procesuiramo podatke, Koja su prava naših korisnika u smislu obrade ličnih podataka, Sa kim delimo podatke</div>
                <div className={styles.title}>Administrator ličnih podataka</div>
                <div className={styles.desc}>Pojedini izrazi korišćeni u ovim Uslovima korišćenja imaju sledeće značenje:„Usluga“ je činjenje dostupnim Korisniku Sadržaja koji se objavljuje na sajtu i/ili aplikaciji, u lične i nekomercijalne svrhe; Ringier Serbia d.o.o. (“Kompanija”) pruža, a Korisnik koristi Uslugu, pristupajući Sadržaju; „Korisnik“ (u množini: „Korisnici“) je lice odnosno lica, fizička ili pravna, strana ili domaća, koja koriste Uslugu, bez obzira na vrstu uređaja sa kojeg pristupaju, vreme pristupa, trajanje korišćenja Usluge, kao i bez obzira na fizičku ili elektronsku adresu sa koje pristupaju sajtu i/ili aplikaciji; „Sadržaj“ podrazumeva tekst, skripte, grafiku, slike, zvukove, video, audio-vizuelne kombinacije, interaktivne funkcije i drugi materijal koji se objavljuje na sajtu i/ili aplikaciji kojem se može pristupiti, bez obzira na oblik saopštavanja Korisniku; “Sajt” je internet sajt “HakatonArena.com” koji se objavljuje na adresi www.HakatonArena.com I koji je u vlasništvu kompanije; “</div>
                <div className={styles.title}>Koji vaši podaci se prikupljaju i u koju svrhu?</div>
                <div className={styles.desc}>Sastavni deo ovih Uslova korišćenja su Politika privatnosti i Politika o kolačićima.</div>
                <div className={styles.desc}>Administrator vaših ličnih podataka je Izdavačko društvo Ringier Serbia d.o.o Beograd, ul. Kosovska br. 10, MB: 17134990, koje je rukovalac i obrađivač podataka, a čiji veb sajt ili aplikaciju koristite. Šta to znači? Pristajanjem na ove Uslove korišćenja, dajete saglasnost Izdavačkom društvu Ringier Serbia d.o.o. da prikuplja i obrađuje prikupljene lične podatke te da odlučuje o ciljevima i metodama obrade vaših ličnih podataka, tj.kako će se vaši podaci koristiti.</div>
                <div className={styles.desc}>Vaše podatke o ličnosti možemo da prikupljamo i obrađujemo radi omogućavanja pristupa određenim sadržajima - prilikom kreiranja Korisničkog naloga; radi ispunjenja zakonskih obaveza.</div>
                <div className={styles.desc}>Prilikom posete i korišćenja našeg sajta isključivo u informativne svrhe, odnosno ukoliko se ne registrujete ili nam vaše lične podatke ne date na neki drugi način, prikupljamo samo one vaše lične podatke koje prenosi vaš internet pretraživač, a što je tehnički neophodno kako bismo mogli da Vam prikažemo naš sajt i da obezbedimo stabilnost i sigurnost.</div>
                <div className={styles.desc}>Isključivo nakon vašeg izričitog pristanka na korišćenje podataka, vaši će podaci biti čuvani i upotrebljeni za svrhe navedene u ovoj Politici privatnosti. Podaci se čuvaju na “cloud” serverima kompanije “Amazon” i pristup podacima imaju samo ovlašćena lica kompanije.</div>
                <div className={styles.desc}>Svrha prikupljanja navedenih podataka o ličnosti je kreiranje Korisničkog naloga na Blic sajtu i/ili aplikaciji kao i svrha ostvarenja legitimnog interesa Kompanije i naših pouzdanih partnera - slanja reklamnih obaveštenja. Podatke prikupljamo od lica na koje se podaci odnose, i to na način da nam ih oni dostave. Podaci se na ovaj način prikupljaju prilikom kreiranja Korisničkog naloga, pri čemu ako želite da kreirate Korisnički nalog, obavezni ste da nam dostavite važeću email adresu. Pored toga, po svom izboru, u predviđena polja na podešavanjima svog naloga možete uneti i sledeće podatke: pol; datum rođenja; zemlja; obrazovanje; ogranak; profesija;broj mobilnog telefona; Na osnovu Vašeg dobrovoljnog pristanka za obradu podataka od strane Ringier Serbia d.o.o., vaše lične podatke nam takođe ustupate: za beleženje istorije pregledanja naših veb sajtova i aplikacija, u marketinške svrhe (uključujući automatizovanu analizu vaših interesovanja, i to isključivo u cilju plasiranja Vama odgovarajućih reklamnih poruka), sve uključujući i postavljanje kolačića na Vašem uređaju (videti dalje Politiku kolačića).</div>
                <div className={styles.desc}>Data saglasnost se odnosi i na obradu Vaših ličnih podataka u marketinške svrhe od strane naših pouzdanih partnera i pristajanjem na Uslove korišćenja, saglasni ste da kompanija Ringier Serbia d.o.o može vašu e-mail adresu ustupati svojim pouzdanim partnerima. Spisak naših pouzdanih partnera možete pronaći u poruci o traženju saglasnosti pod linkom "Promeni postavke". Saglasni ste da primate reklamna obaveštenja Kompanije i njenih pouzdanih partnera.</div>
                <div className={styles.title}>Po kom osnovu obrađujemo podatke</div>
                <div className={styles.desc}>Zakonski osnov obrade podataka o ličnosti je vaš pristanak kao lica na koje se podaci odnose, izvršenje ugovorne obaveze kao i legitimni interes rukovaoca iz člana 12 Zakona o zaštiti podataka o ličnosti (dalje: ZZPL).</div>
                <div className={styles.title}>Koliko dugo obrađujemo podatke?</div>
                <div className={styles.desc}>Vaši podaci će biti obrađivani do: - u slučaju davanja saglasnosti do trenutka opoziva saglasnosti za obradu, ograničenja ili druge radnje kojom se ograničava data saglasnost, - u slučaju potrebe da se Vaši podaci koriste za realizaciju ugovora, do isteka trajanja ugovorne obaveze - ako je osnov za obradu podataka naš legitimni interes, i to do podnošenja prigovora ili opoziva saglasnosti, - za poreske i računovodstvene svrhe u meri i u roku, koji je u skladu sa drugim važećim propisima.</div>
                <div className={styles.title}>Koja su vaša prava u slučaju obrade ličnih podataka?</div>
                <div className={styles.desc}>U skladu sa odredbama Opšte Uredbe o zaštiti ličnih podataka (Uredbe Evropskog parlamenta i Saveta (EU) 2016/679 koja se primenjuje od 25.05.2018. godine) i Zakona o zaštiti podataka o ličnosti Republike Srbije ("Sl. glasnik RS", br. 87/2018), imate sledeća prava u odnosu na obradu ličnih podataka sa naše strane, uključujući i obradu ličnih podataka i od strane naših pouzdanih partnera: - pravo pristupa svojim podacima, uključujući i dobijanje kopije podataka, - pravo na zahtevanje ispravke podataka, - pravo na brisanje podataka, - pravo na podnošenje žalbe nadzornom organu za zaštitu ličnih podataka, - pravo ograničavanja obrade podataka.</div>
                <div className={styles.desc}>Ako se vaši podaci obrađuju na osnovu saglasnosti, imate pravo da opozovete vašu prethodno datu saglasnost. Opoziv saglasnosti ne utiče na zakonitost obrade koja je izvršena na osnovu saglasnosti pre vašeg opoziva.</div>
                <div className={styles.desc}>Ako se vaši podaci obrađuju na osnovu saglasnosti ili u svrhu ugovora (potrebnog za pružanje usluge), imate pravo na prenos ličnih podataka.</div>
                <div className={styles.desc}>Pravo lica na prenosivost podataka znači pravo da svoje podatke o ličnosti koje ste prethodno dostavili Kompaniji dobijete u uobičajeno korišćenom i elektronski čitljivom obliku i imate pravo da takve podatke prenesete drugom rukovaocu.</div>
                <div className={styles.desc}>Imate pravo na ispravku podataka o ličnosti, odnosno imate pravo podneti zahtev za ispravku vaših netačnih podataka o ličnosti, kao i pravo da dopunite nepotpune podatke o ličnosti, između ostalog i davanjem dodatne izjave.</div>
                <div className={styles.desc}>Pravo na brisanje („pravo na zaborav“) označava vaše pravo na brisanje vaših podataka o ličnosti u sledećim slučajevima:</div>
                <div className={styles.title}>Pravo na prigovor</div>
                <div className={styles.desc}>Imate pravo na prigovor, što znači da imate pravo uložiti prigovor Kompaniji na obradu podataka o ličnosti. Kada uložite prigovor, Kompaniji više nije dozvoljeno da obrađuje vaše podatke o ličnosti, osim ako postoje zakonski razlozi za obradu koji pretežu nad vašim interesima, pravima ili slobodama ili su u vezi sa podnošenjem, ostvarivanjem ili odbranom pravnog zahteva.</div>
                <div className={styles.desc}>O vašem zahtevu za ostvarivanje prava u vezi sa vašim podacima o ličnosti, postupićemo u roku od 30 dana. Ovaj rok može u opravdanim slučajevima biti produžen za još 60 dana.</div>
                <div className={styles.desc}>Nadzorno telo za zaštitu podataka o ličnosti u Republici Srbiji je Poverenik za informacije od javnog značaja i zaštitu podataka o ličnosti, Bulevar kralja Aleksandra 15, Beograd (u nastavku teksta: Poverenik).</div>
                <div className={styles.desc}>Imate pravo da podnese pritužbu Povereniku ako smatrate da je obrada podataka izvršena suprotno odredbama Zakona. Podnošenje pritužbe Povereniku ne utiče na pravo da pokrenete druge postupke upravne ili sudske zaštite. Poverenik je dužan da Vas obavesti o toku postupka koji vodi, rezultatima postupka, kao i o pravu lica da pokrene sudski postupak u skladu sa članom 83. Zakona. Pritužba se podnosi u pisanom obliku, neposredno ili elektronski na obrascu Pritužba, poštom na gornju adresu ili na email: prituzba@poverenik.rs.</div>
                <div className={styles.title}>Kako možete ostvariti svoja prava?</div>
                <div className={styles.desc}>Kako nas kontaktirati u vezi sa ličnim podacima? Za obradu vaših ličnih podataka i sprovođenje vaših prava vezanih za obradu, možete se obratiti na sledeću adresu: e-mail: zastitapodataka@ringier.rs adresa: ul. Kosovska 10, 11 000 Beograd, sa napomenom "Obrada ličnih podataka”</div>
                <div className={styles.title}>Sa kim delimo podatke?</div>
                <div className={styles.desc}>Vaši podaci mogu biti preneti našim pouzdanim partnerima koji obrađuju lične podatke u naše ime, uključujući provajdere IT, marketinške agencije kao i druge naše pouzdane partnere.U slučaju prenosa podataka, mi ćemo zahtevati da naši pouzdani partneri čuvaju tajnost i bezbednost podataka kao i da sprovedu odgovarajuće mere kako bi se obezbedila zaštita podataka o ličnosti.</div>
                <div className={styles.desc}>Vaši podaci mogu biti prosleđeni i drugim privrednim subjektima koji su ovlašćeni za obradu podataka na osnovu važećih zakona Republike Srbije.</div>
            </section>
        </section>
        
    )
}