import styles from "./TermsOfUse.module.css"

export default function TermsOfUSe(){
    
    return(
        <section className={styles.cardsMainSection}>
            <section className={styles.cardsSection}>
                <div className={styles.title}>Uslovi korišćenja sajta</div>
                <div className={styles.desc}>Korišćenjem ovog web sajta i/ili aplikacije, prihvatate ove Uslove korišćenja kao i pravno obavezujući odnos koji se konstituiše između vas kao Korisnika i učenika Beograd, koja je vlasnik ovog web sajta i aplikacije. Prihvatanjem ovih Uslova korišćenja dajete svoj bezuslovni i neopozivi pristanak da ćete se prilikom korišćenja usluge pridržavati ovih Uslova korišćenja.</div>
                <div className={styles.desc}>Pojedini izrazi korišćeni u ovim Uslovima korišćenja imaju sledeće značenje:„Usluga“ je činjenje dostupnim Korisniku Sadržaja koji se objavljuje na sajtu i/ili aplikaciji, u lične i nekomercijalne svrhe; Ringier Serbia d.o.o. (“Kompanija”) pruža, a Korisnik koristi Uslugu, pristupajući Sadržaju; „Korisnik“ (u množini: „Korisnici“) je lice odnosno lica, fizička ili pravna, strana ili domaća, koja koriste Uslugu, bez obzira na vrstu uređaja sa kojeg pristupaju, vreme pristupa, trajanje korišćenja Usluge, kao i bez obzira na fizičku ili elektronsku adresu sa koje pristupaju sajtu i/ili aplikaciji; „Sadržaj“ podrazumeva tekst, skripte, grafiku, slike, zvukove, video, audio-vizuelne kombinacije, interaktivne funkcije i drugi materijal koji se objavljuje na sajtu i/ili aplikaciji kojem se može pristupiti, bez obzira na oblik saopštavanja Korisniku; “Sajt” je internet sajt “HakatonArena.com” koji se objavljuje na adresi www.HakatonArena.com I koji je u vlasništvu kompanije “Ringier Serbia doo”; “Aplikacija” je “HakatonArena” aplikacija za uređaje dostupna na “Apple store” i “Google play” store; „Komentari“ su komentari koje Korisnik objavljuje na sajtu i/ili aplikaciji, „Podaci o korisniku“ su podaci o korisniku/korisnicima koji se automatski prikupljaju prilikom korišćenja Usluge i pristupa Sadržaju i podaci o Korisniku koje Korisnik lično dostavi Kompaniji; „Kolačići“ (Cookies) su mali tekstualni fajlovi koji se u okviru pružanja Usluge, prenose na elektronsku opremu putem koje Korisnik pristupa Sadržaju.</div>
                <div className={styles.desc}>Sastavni deo ovih Uslova korišćenja su Politika privatnosti i Politika o kolačićima.</div>
                <div className={styles.desc}>Otvaranje Korisničkog naloga dozvoljeno je samo licima koja su navršila najmanje 15 godina života, pa prihvatanjem ovih Uslova korišćenja, potvrđujete i garantujete da ste dovoljnog uzrasta za korišćenje Usluge.</div>
                <div className={styles.desc}>Svi sadržaji objavljeni na sajtu i/ili aplikaciji su u isključivom vlasništvu Ringier Serbia d.o.o. i/ili su u vlasništvu njegovih povezanih lica, i/ili su u vlasništvu poslovnih partnera Ringier Serbia d.o.o, te se mogu jedino i isključivo koristiti za ličnu upotrebu i u nekomercijalne svrhe</div>
                <div className={styles.desc}>Nije dozvoljeno umnožavanje, reprodukovanje, javno prikazivanje ili distribuiranje Sadržaja ili bilo kog dela Sadržaja sa sajta ili aplikacije, bez prethodnog pisanog odobrenja ili pisane saglasnosti učenika</div>
                <div className={styles.desc}>Sadržaj sajta i/ili aplikacije kao i svi delovi Sadržaja predstavljaju zaštićeno autorsko pravo koje pripada Ringier Serbia d.o.o, odnosno isti je u režimu zaštićenog autorskog prava trećih lica koja su prenela pravo korišćenja istih na kompaniju Ringier Serbia d.o.o. Korišćenjem Sadržaja ne stičete vlasništvo na bilo kom delu Sadržaja kojem pristupate</div>
                <div className={styles.desc}>Intelektualna svojina, uključujući sve zaštićene znakove, logo znakove, tekstove, podatke, fotografije i/ili grafizme, kao i celokupan Sadržaj dostupan na sajtu i/ili aplikaciji je u isključivom vlasništvu učenika ili je u vlasništvu trećih lica koja su prenela pravo korišćenja istih na kompaniju Ringier Serbia d.o.o.</div>
                <div className={styles.desc}>Nepoštovanje Uslova korišćenja, odnosno neovlašćeno korišćenje Sadržaja uključujući ali ne ograničavajući se na umnožavanje, kopiranje, emitovanje, činjenje dostupnim na bilo koji drugi način, putem bilo kog medijuma, predstavlja povredu tih prava shodno pozitivnim propisima važećim u Republici Srbiji te podleže građanskoj I krivičnoj odgovornosti.</div>
                <div className={styles.desc}>Na sve sporne odnose između ugovornih strana koji nastanu usled korišćenja Usluge, primenjivaće se pravo Republike Srbije, a u slučaju eventualnog spora, ugovara se nadležnost suda u Beogradu. Učenici zadržavaju pravo da u bilo kom trenutku, bez prethodne najave ,izmeni ove Uslove korišćenja i neće biti odgovorna ni za kakve moguće posledice proizašle iz promena Uslova korišćenja. Promene uslova korišćenja stupaju na snagu u trenutku objavljivanja na sajtu.</div>
                <div className={styles.title}>Odricanje i ograničenje od odgovornosti</div>
                <div className={styles.desc}>Sadržaj koji se nalazi na sajtu i/ili aplikaciji, ili bilo koji deo predmetnog Sadržaja ne može se smatrati ponudom ili pozivom na kupovinu bilo koje imovine ili prava, niti se isti ima ili može smatrati dovoljnom informacijom za donošenje značajnih ličnih, finansijskih ili poslovnih odluka.</div>
                <div className={styles.desc}>Celokupan Sadržaj, koji pored intelektualne svojine uključuje i objavljivanje informacija, mišljenja, analiza, zaključaka, prognoza i projekcija, podložan je izmenama. Učenici zadržavaju pravo da u svakom trenutku, po svom izboru izvrši izmenu ili uklanjanje Sadržaja.</div>
                <div className={styles.desc}>Određeni deo Sadržaja koji se prikazuje na sajtu i/ili aplikaciji obezbeđuju treća lica (baneri, pop-up i sl.). Učenici nisu odgovorni za sadržaje trećih lica ni u kom delu.</div>
                <div className={styles.desc}>Prihvatanjem ovih Uslova korišćenja saglasni ste i razumete da se Sadržaj isporučuje Korisnicima takav kakav je, u obliku u kojem je učinjen dostupnim, sa svim eventualnim greškama i bez bilo kakvih izričitih ili prećutnih garancija u pogledu kvaliteta ili količine Sadržaja ili funkcionisanja sajta i/ili aplikacije. Kompanija Kompanija Ringier Serbia d.o.o. ne garantuje da će pružanje usluge preko sajta i/ili aplikacije biti bez grešaka ili prekida u radu i pouzdanje u funkcionisanje Usluge je u potpunosti rizik Korisnika.</div>
                <div className={styles.desc}>Učenici ESTŠ "Nikola Tesla" Kraljevo ni u kom slučaju neće biti odgovorna za nefunkcionisanje Usluge, kao ni za smetnje, kašnjenja ili prekide u njenom funkcionisanju, koji su prouzrokovani uticajima van kontrole Aplikacije, a koji se nisu mogli predvideti, sprečiti ili izbeći, uključujući bez bilo kakvih ograničenja: obustave rada, štrajkove, nesreće, tehničke smetnje, neispravnosti programa ili sredstava komunikacija (softvera ili hardvera), nemire, ratove, odluke nadležnih organa i dr. Učenici će u ovakvim slučajevima uložiti svoje najbolje napore koji su u skladu sa poslovnom praksom, kako bi u što hitnijem roku omogućila nesmetano funkcionisanje Usluge.</div>
                <div className={styles.desc}>Razumete I saglasni ste da nijedan učenik nije odgovorna za bilo kakvu štetu (materijalnu ili nematerijalnu, direktnu ili indirektnu, stvarnu ili buduću) ili bilo kakve gubitke ili izmaklu korist koji bi mogli da nastanu usled: nefunkcionisanja usluge i to sajta i/ili aplikacije; nemogućnosti upotrebe sajta i/ili aplikacije; performansi sajta i/ili aplikacije; bilo kakvih grešaka ili propusta u radu sajta ili aplikacije; kao ni za bilo kakvo oštećenje računara, mobilnog uređaja ili druge opreme ili tehnologije bilo kojeg korisnika koji bi nastali u vezi sa korišćenjem sajta i/ili aplikacije, uključujući, ali ne ograničavajući se na štetu od bilo kakvog kršenja bezbednosti, privatnosti ili računarskog virusa, greške, prevare, prekida u radu, kvara na uređaju ili mreži ili bilo koje druge smetnje uključujući, ali ne ograničavajući se na gubitak podataka, kvarove ili neispravnost uređaja.</div>
                <div className={styles.desc}>Razumete i prihvatate da učenici pružanju najbolje od svojih usluga koristi servise trećih lica (“Dobavljači”) koja nisu pod kontrolom učenika ne daje bilo kakve garancije i neće biti odgovorna za postupke ili propuštanja bilo kog dobavljača kao ni za nefunkcionisanje servisa dobavljača. U slučaju smetnji u radu servisa dobavljača, Kompanija će uputiti Korisnike da se obrate direktno dobavljaču I uložiće razumne napore sa svoje strane da omogući pravilno i potpuno funkcionisanje Usluge.</div>
                <div className={styles.title}>Obaveze posetilaca/korisnika sajta</div>
                <div className={styles.desc}>U cilju efikasnog, bezbednog i neometanog korišćenja sadržaja koji se nalazi na web sajtu i/ili aplikaciji nije dozvoljeno:</div>
                <div className={styles.desc}>a objavljivanje, slanje, razmenjivanje i prenošenje sadržaja koje je u suprotnosti sa važećim propisima; b- objavljivanje, slanje, razmenjivanje i prenošenje uvredljivog, vulgarnog, pretećeg, rasističkog ili šovinističkog sadržaja, kao i sadržaja koji na bilo na bilo koji način može da prouzrokuje štetu bilo kom licu; c- objavljivanje, slanje, razmenjivanje i prenošenje informacija za koje posetilac zna ili pretpostavlja da su lažne ili kojima se povređuju prava drugih lica; d- lažno predstavljanje, odnosno predstavljanje u ime drugog, pravnog ili fizičkog lica; e- manipulisanje i zloupotreba identifikatorima da bi se prikrilo poreklo sadržaja koji se objavljuje, šalje, razmenjuje ili prenosi; f- objavljivanje, razmena i slanje neželjenog sadržaja korisnika bez njihovog pristanka ili traženja, kao što su promotivni materijali, reklamne poruke, spam poruke, lančana pisma, promotivni i reklamni materijali koji sadrže lažne informacije, navode ili tvrdnje koje mogu zavarati korisnike; h- objavljivanje, slanje, razmenjivanje i prenošenje sadržaja s virusima ili sličnim štetnim fajlovima ili programima; i- prikupljanje, čuvanje i objavljivanje ličnih podataka drugih posetilaca sajta i/ili aplikacije.</div>
                <div className={styles.desc}>Zadržavamo pravo da uklonimo sadržaj koji smatramo neprimerenim ili koji nije u skladu sa Uslovima korišćenja. Korisnici preuzimaju odgovornost za svaku štetu koja nastane kao posledica njihovih aktivnosti.</div>
                <div className={styles.title}>Korisnički nalozi i članstvo</div>
                <div className={styles.desc}>Da biste pristupili određenim uslugama koje pružamo, potrebno je da imate aktivan Korisnički nalog.</div>
                <div className={styles.desc}>Kada otvorite nalog na sajtu i/ili aplikaciji, u celosti ste odgovorni za održavanje bezbednosti sopstvenog naloga kao i za sve aktivnosti koje se dešavaju u okviru vašeg naloga, kao i bilo koje druge radnje koje su preduzete u vezi sa nalogom. U cilju bezbednosti, nemojte odavati bilo kome vašu korisničku lozinku. Davanje netačnih kontakt informacija bilo koje vrste biće sankcionisano gašenjem naloga. Obavezni ste da bez odlaganja prijavite svaku zloupotrebu svog korisničkog naloga. U slučaju neovlašćene upotrebe naloga od strane trećih lica, kompanija Ringier Serbia d.o.o. neće biti odgovorna za radnje ili propuste, uključujući i bilo kakvu štetu bilo koje vrste u vezi sa takvim radnjama ili propustima.</div>
                <div className={styles.desc}>Zadržavamo pravo suspenzije ili uklanjanja korisničkog naloga ili bilo kog njegovog dela, ako se utvrdi da je Korisnik naloga prekršio bilo koju obavezu Uslova korišćenja ili je ponašanje korisnika imalo tendenciju da prouzrokuje bilo kakvu vrstu štete.</div>
            </section>
        </section>
        
    )
}